version: "3"
services:
  jenkins:
    container_name: jenkins
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8080:8080
      - 5000:5000
      - 50000:50000