version: "3"
services:
  jenkins:
    container_name: jenkins
    build: .
    volumes:
      - $PWD/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 8080:8080
      - 5000:5000